export const GET_CARS_LIST = 'GET_CARS_LIST';
export const GET_CARS_LIST_SUCCESS = 'GET_CARS_LIST_SUCCESS';
export const GET_CARS_LIST_FAILURE = 'GET_CARS_LIST_FAILURE';

export const GET_CAR_DETAILS = 'GET_CAR_DETAILS';
export const GET_CAR_DETAILS_SUCCESS = 'GET_CAR_DETAILS_SUCCESS';
export const GET_CAR_DETAILS_FAILURE = 'GET_CAR_DETAILS_FAILURE';

export const GET_FILTER_COLORS = 'GET_FILTER_COLORS';
export const GET_FILTER_COLORS_SUCCESS = 'GET_FILTER_COLORS_SUCCESS';
export const GET_FILTER_COLORS_FAILURE = 'GET_FILTER_COLORS_FAILURE';

export const GET_FILTER_MANUFACTURERS = 'GET_FILTER_MANUFACTURERS';
export const GET_FILTER_MANUFACTURERS_SUCCESS = 'GET_FILTER_MANUFACTURERS_SUCCESS';
export const GET_FILTER_MANUFACTURERS_FAILURE = 'GET_FILTER_MANUFACTURERS_FAILURE';

export const SET_FILTERS = 'SET_FILTERS';
export const SET_SORT_ORDER = 'SET_SORT_ORDER';
